### ISSUE TITLE
Fix toasts for deleted

### ISSUE THREAD

**Issue by PGMacDesign** [Jazzeroki/LacunaExpress#19]
Need to fix the toasts popping up in the various read mail activity functions that call a toast afterwards to match the action. All just read deleted now, should read something like, "reply sent"

**Comment by PGMacDesign** [comment]
This is also an issue in the compose message activities and reply activities where the toast, "DELETED" is popping up when "sent" or something else should come up instead.

**Comment by Jazzeroki** [comment]
Need to look at a bit more.  But I think I fixed it.  At least for reply anyways need to look at compose.
