### ISSUE TITLE
Widget count doesn't update

### ISSUE THREAD

**Issue by tmtowtdi** [Jazzeroki/LacunaExpress#25]
Upon creating the widget, it correctly shows how many correspondence mails are in my inbox (2).  I sent myself a test message (giving me 3 in my inbox).  After several hours, the widget still reports 2 messages, and no notification ever came in about the third one (I did set notifications on the widget).

I created a second widget, also for correspondence mails, and that one is reporting 3 messages upon creation, while the original widget still reports 2.

**Comment by PGMacDesign** [comment]
Isolated first issue with updates. Seems issue is that the service is not
firing. Will work on changing service extensions in the next couple days

**Comment by PGMacDesign** [comment]
Update issue has been fixed, but working to redesign the code to work with a content provider and an SQLite database for smoother refreshes.

**Comment by tmtowtdi** [comment]
Closing because TLE is dead.
